version: '3.8'

services:     
  prometheus:
    build:
      dockerfile: ./Dockerfile
      context: ./monitoring/prometheus
    image: prometheus_image
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    build:
      dockerfile: ./Dockerfile
      context: ./monitoring/grafana
    image: grafana_image
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - /root/itu-minitwit/grafana/data:/var/lib/grafana

volumes:
  grafana-storage: { }