services:
  prometheus:
    build:
      dockerfile: ./Dockerfile
      context: ./monitoring/prometheus
    image: prometheus_image
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
  grafana:
    build:
      dockerfile: ./Dockerfile
      context: ./monitoring/grafana
    image: grafana_image
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
  
  loki:
    image: grafana/loki:3.6.7
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./logging/loki/loki-config.yml:/etc/loki/local-config.yaml
      - /root/itu-minitwit/loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

volumes:
  db_data:
  grafana-storage: { }