{
 "title": "Business Intelligence Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Top 10 Most Followed",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(minitwit_most_followed)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "minitwit_total_users", "legendFormat": "__auto" },
    { "expr": "minitwit_active_users", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total cheeps in the 24 hours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "minitwit_total_cheeps_posted", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average followers on users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "minitwit_average_followers", "legendFormat": "__auto" }
   ]
  }
 ]
}