services:
  prometheus:
    build:
      dockerfile: ./Dockerfile
    image: prometheus_image
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - monitoring

volumes:
  db_data:
    
networks:
  monitoring:
    external: true